CREATE TABLE `rest_aspnet`.`users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(50) NOT NULL DEFAULT 0,
  `Password` VARCHAR(130) NOT NULL DEFAULT 0,
  `FullName` VARCHAR(120) NOT NULL,
  `RefreshToken` VARCHAR(500) NULL DEFAULT 0,
  `RefreshTokenExpiryTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;