version: '3.4'

services:
  db:
    image: rest_aspnet_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_aspnet
    ports:
      - 3308:3306
    networks:
      - rest-aspnet-network
  
  rest_aspnet:
    image: rest_aspnet
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 4430:80
    depends_on:
      - db
    networks:
      - rest-aspnet-network
networks:
  rest-aspnet-network:
    driver: bridge
